uui-input-file => Only show add button when multiple or no file selected
umbraco/Umbraco.UI pull request #395
Opened 2023-01-13 01:23 UTC by nathanwoulfe

## Description

Change updates uui-input-file to only show the add button only when multiple is true, or when no files are selected (single-file mode).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Motivation and context

The picker works correctly in it's current shape (ie single mode only allows one file, multiple allows many), I'm just not sure the UI makes sense - continuing to display the Add button after selecting a file in single mode is potentially confusing, even though the button will replace the existing selection. 

Alternatively could consider changing the button text when a file is selected in single-mode (ie `Replace` or `Change selection` or something similar)

I won't lose a minute of sleep if the current implementation is preferred.

## How to test?

## Screenshots (if appropriate)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/dev/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

2023-01-27 08:53 UTC, iOvergaard commented
Hi @nathanwoulfe 
I think you might be right here, but something's happened with Storybook, where the story for a prevalue doesn't look right anymore (it should show the selected image). Also, the build is failing because of linting issues :-)

2023-01-27 08:54 UTC, iOvergaard requested changes
Hi @nathanwoulfe
I think you might be right here, but something's happened with Storybook, where the story for a prevalue doesn't look right anymore (it should show the selected image). Also, the build is failing because of linting issues :-)

2023-01-30 04:38 UTC, nathanwoulfe commented
Heya @iOvergaard, should be better now - was missing an import, which broke the story.

2023-01-30 13:57 UTC, iOvergaard approved these changes

2023-01-30 13:58 UTC, merged