Feature/popover container firefox polyfill
umbraco/Umbraco.UI pull request #628
Opened 2023-10-26 09:40 UTC by JesmoDev

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Motivation and context

## How to test?

## Screenshots (if appropriate)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/dev/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

2023-11-03 10:58 UTC, bjarnef commented
Not sure if it worth trying this project:
https://github.com/oddbird/popover-polyfill

Based on the demos it seems to work in Firefox:
https://popover-polyfill.netlify.app/

2023-11-07 07:33 UTC, JesmoDev commented
@bjarnef I've looked at the oddbird polyfill, and I can't get it to work properly in bigger applications such as New Backoffice due to z-index issues.

2023-11-08 08:33 UTC, iOvergaard requested changes
We agreed on the following:

- Clean up the popover container story (remove test)
- Change experimental warning to say that it now _will_ work in all browsers due to a polyfill (but it is still experimental)
- Make it 1-1 with the old popover stories
- Add deprecation warnings to the old Popover element

2023-11-08 09:59 UTC, iOvergaard approved these changes

2023-11-08 10:12 UTC, merged