Adds UUI-Copy
umbraco/Umbraco.UI pull request #985
Opened 2024-12-23 23:18 UTC by warrenbuckley

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Motivation and context

## How to test?

## Screenshots (if appropriate)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/v1/contrib/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

2024-12-23 23:29 UTC, warrenbuckley commented
I am open for discussion and feedback to improve this
/cc @iOvergaard & @nielslyngsoe

2025-01-03 14:08 UTC, warrenbuckley commented
I may need some pointers or advice with the tests please @nielslyngsoe or @iOvergaard

2025-01-07 10:02 UTC, iOvergaard requested changes
Looks good, but I am not sure how to fix the tests. It says the browser asked for permission to copy but the user denied it, so we probably need Playwright to launch the browser with a special parameter to allow non-user interaction...?

Important to me is that we can use this inside the `<umb-code-block>` element in the Backoffice. Did you try and test it there yet?

2025-01-07 12:01 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +      const el = document.getElementById(this.copyFrom);
@iOvergaard AFAIK this is the same as Shoelace approach so it will not target any IDs inside another custom element with its own shadow DOM.

2025-01-07 12:06 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +import { UUIButtonElement } from '@umbraco-ui/uui-button/lib';
@iOvergaard yep see line 80 do a cast of the event target as UUIButtonElement
`const button = e.target as UUIButtonElement;`

2025-01-07 12:17 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +  color: 'default' | 'positive' | 'warning' | 'danger' = 'default';
Done - removed the `reflect:true`

2025-01-07 12:22 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> + * @dependancy uui-icon
Yep all done - wasn't aware of that util function

2025-01-07 13:28 UTC, warrenbuckley commented
>Important to me is that we can use this inside the <umb-code-block> element in the Backoffice. Did you try and test it there yet?

I wouldn't know how to do that @iOvergaard as its over in the CMS repo, is there something I can do to try/test this out then?

2025-01-07 13:41 UTC, iOvergaard commented
> > Important to me is that we can use this inside the  element in the Backoffice. Did you try and test it there yet?
> 
> I wouldn't know how to do that @iOvergaard as its over in the CMS repo, is there something I can do to try/test this out then?

You can run `npm link` in the **uui-copy** folder, then go over to your Backoffice installation and run `npm link @umbraco-ui/uui-copy` there, and it should then be available. You may need to run `npm run build` first in the uui-copy folder.

2025-01-07 15:00 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +        button.state = 'success';
I have set it to 2 seconds but not sure if it looks odd/weird to me @iOvergaard 

https://github.com/user-attachments/assets/67143081-0fe1-4406-a310-1901eb23d033

2025-01-07 16:27 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +        button.state = 'success';
Changed it to 250ms as the default as per your suggestion via Slack and also set it as a property so it can be changed/overriden.

2025-01-07 16:58 UTC, warrenbuckley commented
Ready for a re-review and see what you think @iOvergaard

2025-01-09 13:15 UTC, iOvergaard requested changes
Functionally, this is exactly what we want to have. I have included some suggestions based on feedback from the team at HQ to optimize the package and the component even further. Please let me know if you would like to take it to the finish line or if we should take over.

2025-01-09 13:15 UTC, iOvergaard commented on packages/uui-copy/lib/uui-copy.element.ts
> +export class UUICopyElement extends LabelMixin('', LitElement) {
Good that you extend the LabelMixin now, @warrenbuckley. I mentioned it to @nielslyngsoe and he was asking why we don't just extend the **UUIButtonElement** itself as we only ever have a `<uui-button></uui-button>` in the rendered output. If you extend from **UUIButtonElement**, you can remove many of the properties from **uui-copy** as they would already be present there.

2025-01-09 13:15 UTC, iOvergaard commented on packages/uui-copy/lib/uui-copy.element.ts
> +@defineElement('uui-copy')
Brought the name of the component up with the team as well. Seeing that it is functionally a button, we would prefer to rename it to something a little more descriptive, e.g. **uui-text-copy-button** to indicate that it is a _button_ that copies _text_ (you can copy all sorts of things in the browser these days and we wouldn't want to confuse it with anything else like a **Copy block** button for instance).

2025-01-09 13:15 UTC, iOvergaard commented on packages/uui-copy/lib/uui-copy.element.ts
> +import { UUIButtonElement } from '@umbraco-ui/uui-button/lib';
Then I would suggest if we can import only the type:

```suggestion
import type { UUIButtonElement } from '@umbraco-ui/uui-button/lib';
```

This means you will probably have to import the button explicitly in Storybook as well as the test files.

2025-01-09 13:16 UTC, iOvergaard commented on packages/uui-copy/lib/index.ts
Missed this in my review: You need to export the **UUICopyEvent** from this file to be able to use it in other packages.

2025-01-11 19:39 UTC, warrenbuckley commented on packages/uui-copy/lib/uui-copy.element.ts
> +export class UUICopyElement extends LabelMixin('', LitElement) {
My question to you both @iOvergaard & @nielslyngsoe is that as this is not a typical Form Control and inherting/extending from UUIButton which in turn extends with the mixin `UUIFormControlMixin` which in turn already has a `value` field.

So can you let me still if you want me to extend from UUIButton, as it seems extra bloat to me to participate as a native form control when it will never be used as part of a form submission.

2025-01-14 15:22 UTC, iOvergaard requested changes
I would say this looks fine and I accept your premise that it is indeed not a form control, thus it doesn't make sense to extend uui-button.

I have suggested a few quick fixes here, but what remains to be tested is to use it inside the backoffice in the code snippet or sysinfo element. I will try to see to that later on.

2025-01-14 15:22 UTC, iOvergaard commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +      });
Consider making a try/catch statement around this rather than `then` and `catch`.

2025-01-14 15:22 UTC, iOvergaard commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +        console.error(`Element ID ${this.copyFrom} not found to copy from`);
A few console.log statements here that should be removed

2025-02-04 00:09 UTC, bjarnef commented
Perhaps we can combine part of the copy method in a utility function similar to this:
https://github.com/Georgegriff/copy-component/blob/main/CopyComponent.js

2025-02-04 20:16 UTC, nielslyngsoe commented
Hi @warrenbuckley 

For maintainability (less code) and to ensure fully working features, focus, labels, etc. then extending `UUIButtonElement` and append the icon by overwritting renderLabel would be my recommendation. It should mainly involve removing code. Stories etc should stay the same.

2025-02-04 20:19 UTC, nielslyngsoe commented on packages/uui-text-copy/lib/UUITextCopyEvent.ts
> +      ...{ bubbles: true },
Any reason for this event to bubbles? I think it shouldn't bubble, but maybe you have a reason?

2025-02-06 10:45 UTC, warrenbuckley commented on packages/uui-text-copy/lib/UUITextCopyEvent.ts
> +      ...{ bubbles: true },
I was probably doing it for the example/story to allow people to catch the event @nielslyngsoe 
If you think I should remove it, I will do

2025-02-08 20:59 UTC, warrenbuckley commented
> For maintainability (less code) and to ensure fully working features, focus, labels, etc. then extending `UUIButtonElement` and append the icon by overwritting renderLabel would be my recommendation. It should mainly involve removing code. Stories etc should stay the same.

Heya @nielslyngsoe my notes on this to @iOvergaard was the concern that this copy button does not make sense to be part of a Form Control and probably does not need some of those complexities and things to be set and or accessible on this copy button.

If you are generally happy all in all, then please make any tweaks or changes you see fit, if you are to consider this as an accepted PR.

Cheers,
Warren 😄

2025-02-13 12:43 UTC, nielslyngsoe commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +  #valueToCopy = '';
I dont see #valueToCopy to be a class property, it could be a `let` inside the function below.

2025-02-13 12:53 UTC, nielslyngsoe commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +@defineElement('uui-text-copy')
Could we call this `uui-string-copy-button` and then it should be extending uui-button so we do not need to property drill so much. :-)

2025-02-13 12:53 UTC, nielslyngsoe commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +        this.#valueToCopy = el.textContent ?? el.innerText ?? '';
First do this when we have proven that there is no `'value' in el`

2025-03-03 21:08 UTC, nielslyngsoe commented on packages/uui-text-copy/lib/uui-text-copy.element.ts
> +@defineElement('uui-text-copy')
Just to summen up, based on the conversation above, this component should and can inherit from `<uui-button>` and it should not be a problem that it is a form control, just as any other button is a form controll. Because as long as you do not give it a `name` attribute it will not be part of your Form Data. (Also I do not think many uses Form Data any longer to construct a data-set.

Quote from the interweb: "only fields (“controls”) that have a name attribute contribute to the form data set."

2025-03-03 21:20 UTC, bjarnef commented
A note off-topic regarding drag handle:
https://github.com/umbraco/Umbraco-CMS/pull/18519#issuecomment-2691453646

I noticed one of these libraries had a copy button as well (as inspiration):
https://f36.contentful.com/components/copy-button

Not sure how relevant it is, but some props can probably be inherited from `<uui-button>`.

2025-03-04 14:07 UTC, iOvergaard approved these changes

2025-03-04 14:11 UTC, merged

2025-03-04 14:24 UTC, bjarnef commented
@iOvergaard it would be great if we had a `copy` utilty function to re-use as mentioned here: https://github.com/umbraco/Umbraco.UI/pull/985?notification_referrer_id=NT_kwDOACyNs7MxMzk5MDQ2NTE3NzoyOTE5ODU5#issuecomment-2632460062

As the copy of color in color picker and this could share this feature :)

2025-03-04 14:29 UTC, iOvergaard commented
@bjarnef Maybe, but do you think it is worth any effort to wrap the one-liner that is `navigator.clipboard.writeText(text)` in a function?

2025-03-04 14:44 UTC, bjarnef commented
@iOvergaard it did a bit more here: https://github.com/Georgegriff/copy-component/blob/main/CopyComponent.js#L2C8-L9

but I think it is mainly for older browsers not supporting `clipboard`, so the part in `else` is probably not needed.

Perhaps `try/catch` or if we want it to return a `Promise`.

I haven't checked what happens if copy fails though.